import { Plus_Jakarta_Sans, Inter } from "next/font/google";
import Loader from "@/components/Loader";
import "./globals.css";

const plusJakarta = Plus_Jakarta_Sans({
	subsets: ["latin"],
	weight: ["200","300","400","500","600","700","800"],
	variable: "--font-plus-jakarta",
});

const inter = Inter({
	subsets: ["latin"],
	weight: ["300", "400", "500", "600", "700"],
	variable: "--font-inter",
	display: "swap",
});

export const metadata = {
	title: "Shreem Software Solutions",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
		<body
			className={`${plusJakarta.variable} ${inter.variable} inter.variable antialiased bg-primary-gradient`}
		>
		<Loader>{children}</Loader>
		</body>
		</html>
	);
}
